GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenants TO app_user;
ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
