spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:claim}

server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

app:
  datasource:
    migration:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:claim}
  security:
    secure-cookie: true

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: ${JWT_EXPIRATION_HOURS:8}
