spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:claim}
    username: ${DB_USER:claim}
    password: ${DB_PASSWORD:claim}
  flyway:
    enabled: true
    schemas: public
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/claim}
    user: ${FLYWAY_USER:claim}
    password: ${FLYWAY_PASSWORD:claim}
management:
  endpoints:
    web:
      exposure:
        include: health
